name: CI with CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '23'
          cache: 'npm'
      - run: npm install
      - run: npm test   # 如果你仓库没 npm 测试，可以删掉这个 job 或这几行

  deploy:
    needs: check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # 去掉仓库名限制
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: '3.12'  # 如果你仓库有这个文件，就保留；否则改成 python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Dependencies
        run: uv sync --locked
      - name: deploy
        run: uv run mkdocs gh-deploy --force